version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: veera_claims_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: claims_portal
    ports:
      - "5449:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - veera_claims_net

  backend:
    build: ./Backend
    container_name: veera_claims_backend
    ports:
      - "3022:3022"
    depends_on:
      - postgres
    networks:
      - veera_claims_net

  frontend:
    build: ./Frontend
    container_name: veera_claims_frontend
    ports:
      - "9034:80"
    networks:
      - veera_claims_net

  hr:
    build: ./HR
    container_name: veera_claims_hr1
    ports:
      - "9035:80"
    networks:
      - veera_claims_net

volumes:
  db_data:

networks:
  veera_claims_net:

